<?php

namespace Rosalana\Safepoint\Support;

class SafepointWriter
{
    /**
     * Assemble the final safepoint.ts file content.
     *
     * @param array<array{name: string, attributes: array<string, string>, relations: array<string, string>}> $models
     * @param array<string, array{method: string, params: string, body: string, props: string}> $routes
     * @param string $sharedData  The TS type body for SharedData (already formatted)
     */
    public function write(array $models, array $routes, string $sharedData): string
    {
        $sections = array_filter([
            $this->header(),
            $this->modelsSection($models),
            $this->routesSection($routes),
            $this->sharedDataSection($sharedData),
            $this->helpersSection(),
        ]);

        return implode(PHP_EOL . PHP_EOL, $sections) . PHP_EOL;
    }

    private function header(): string
    {
        return <<<'TS'
        // This file is auto-generated by rosalana/safepoint.
        // Do not edit this file directly, any changes will be overwritten.
        // Run `php artisan safepoint:generate` to regenerate.
        TS;
    }

    private function modelsSection(array $models): string
    {
        if (empty($models)) {
            return '';
        }

        $interfaces = [];

        foreach ($models as $model) {
            $interfaces[] = $this->modelInterface($model);
        }

        return '// --- Models --- //' . PHP_EOL . PHP_EOL . implode(PHP_EOL . PHP_EOL, $interfaces);
    }

    private function modelInterface(array $model): string
    {
        $lines = [];
        $lines[] = 'export interface ' . $model['name'] . ' {';

        if (! empty($model['attributes'])) {
            foreach ($model['attributes'] as $key => $type) {
                $lines[] = '  ' . $key . ': ' . $type;
            }
        }

        if (! empty($model['relations'])) {
            if (! empty($model['attributes'])) {
                $lines[] = '';
            }

            foreach ($model['relations'] as $key => $type) {
                $lines[] = '  ' . $key . '?: ' . $type;
            }
        }

        $lines[] = '}';

        return implode(PHP_EOL, $lines);
    }

    private function routesSection(array $routes): string
    {
        if (empty($routes)) {
            return '';
        }

        $lines = [];
        $lines[] = '// --- Routes --- //';
        $lines[] = '';
        $lines[] = 'export interface Routes {';

        foreach ($routes as $name => $route) {
            $lines[] = "  '" . $name . "': {";
            $lines[] = "    method: '" . $route['method'] . "'";
            $lines[] = '    params: ' . $this->indentBlock($route['params'], 4);
            $lines[] = '    body: ' . $this->indentBlock($route['body'], 4);
            $lines[] = '    props: ' . $this->indentBlock($route['props'], 4);
            $lines[] = '  }';
            $lines[] = '';
        }

        // Remove trailing empty line before closing brace
        if (end($lines) === '') {
            array_pop($lines);
        }

        $lines[] = '}';

        return implode(PHP_EOL, $lines);
    }

    /**
     * Indent all lines of a multi-line string (except the first) by $spaces spaces.
     */
    private function indentBlock(string $block, int $spaces): string
    {
        if (! str_contains($block, PHP_EOL)) {
            return $block;
        }

        $pad = str_repeat(' ', $spaces);

        return implode(
            PHP_EOL,
            array_map(
                fn ($line, $i) => $i === 0 ? $line : $pad . $line,
                explode(PHP_EOL, $block),
                array_keys(explode(PHP_EOL, $block)),
            ),
        );
    }

    private function sharedDataSection(string $sharedData): string
    {
        if ($sharedData === '' || $sharedData === 'Record<string, never>') {
            return '';
        }

        return '// --- Shared Data --- //' . PHP_EOL . PHP_EOL
            . 'export interface SharedData ' . $sharedData;
    }

    private function helpersSection(): string
    {
        return <<<'TS'
        // --- Helpers --- //

        type RequiredKeys<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>

        export type PageProps<T extends keyof Routes> =
          Routes[T]['props'] extends never
            ? SharedData
            : Routes[T]['props'] & SharedData

        export type RouteParams<T extends keyof Routes> =
          Routes[T]['params'] extends never
            ? never
            : Routes[T]['params']

        export type RouteBody<T extends keyof Routes> =
          Routes[T]['body'] extends never
            ? never
            : Routes[T]['body']
        TS;
    }
}
