<?php

namespace Rosalana\Safepoint\Support;

class SafepointWriter
{
    /**
     * Assemble the final safepoint.ts file content.
     *
     * @param array<array{name: string, attributes: array<string, string>, relations: array<string, string>}> $models
     * @param array<string, array{method: string, params: string, body: string, props: string}> $routes
     * @param array<string, array{method: string, uri: string}> $routeList
     * @param array<array{name: string, cases: array<string, string>}> $enums
     * @param string $sharedData  The TS type body for SharedData (already formatted)
     * @param array{routes: bool, models: bool, enums: bool, inertia: bool} $writeOptions
     */
    public function write(array $models, array $routes, array $routeList, array $enums, string $sharedData, array $writeOptions): string
    {
        $sections = array_filter([
            $this->header(),
            $writeOptions['routes'] ? $this->imports() : null,
            $this->modelsSection($models),
            $this->enumsSection($enums),
            $this->routesSection($routes),
            $this->sharedDataSection($sharedData),
            $this->routeListSection($routeList),
            $writeOptions['routes'] ? $this->helpersSection() : null,
        ]);

        return implode(PHP_EOL . PHP_EOL, $sections) . PHP_EOL;
    }

    private function header(): string
    {
        return <<<'TS'
        /*
         * Auto-generated by rosalana/safepoint
         * Do not edit directly — changes will be overwritten
         * Run `php artisan safepoint:generate` to regenerate
         */
        TS;
    }

    private function imports(): string
    {
        return <<<'TS'
        import type { PageProps as InertiaPageProps } from '@inertiajs/core';
        TS;
    }

    private function modelsSection(array $models): string
    {
        if (empty($models)) {
            return '';
        }

        $interfaces = [];

        foreach ($models as $model) {
            $interfaces[] = $this->modelInterface($model);
        }

        return '/* --- Models --- */' . PHP_EOL . PHP_EOL . implode(PHP_EOL . PHP_EOL, $interfaces);
    }

    private function modelInterface(array $model): string
    {
        $lines = [];
        $lines[] = 'export interface ' . $model['name'] . ' {';

        if (! empty($model['attributes'])) {
            foreach ($model['attributes'] as $key => $type) {
                $lines[] = '  ' . $key . ': ' . $type;
            }
        }

        if (! empty($model['relations'])) {
            if (! empty($model['attributes'])) {
                $lines[] = '';
            }

            foreach ($model['relations'] as $key => $type) {
                $lines[] = '  ' . $key . '?: ' . $type;
            }
        }

        $lines[] = '}';

        return implode(PHP_EOL, $lines);
    }

    private function enumsSection(array $enums): string
    {
        if (empty($enums)) {
            return '';
        }

        $lines = [];
        $lines[] = '/* --- Enums --- */';
        $lines[] = '';

        foreach ($enums as $enum) {
            $cases = [];

            foreach ($enum['cases'] as $key => $value) {
                $cases[] = $value;
            }

            $lines[] = 'export type ' . $enum['name'] . ' = ' . implode(' | ', array_map(fn($case) => "'" . $case . "'", $cases)) . ';';
        }

        return implode(PHP_EOL, $lines);
    }

    private function routesSection(array $routes): string
    {
        if (empty($routes)) {
            return '';
        }

        $lines = [];
        $lines[] = '/* --- Routes --- */';
        $lines[] = '';
        $lines[] = 'export interface Routes {';

        foreach ($routes as $name => $route) {
            $lines[] = "  '" . $name . "': {";
            $lines[] = "    method: '" . $route['method'] . "'";
            $lines[] = '    params: ' . $this->indentBlock($route['params'], 4);
            $lines[] = '    body: ' . $this->indentBlock($route['body'], 4);
            $lines[] = '    props: ' . $this->indentBlock($route['props'], 4);
            $lines[] = '  }';
            $lines[] = '';
        }

        // Remove trailing empty line before closing brace
        if (end($lines) === '') {
            array_pop($lines);
        }

        $lines[] = '}';

        return implode(PHP_EOL, $lines);
    }

    /**
     * Indent all lines of a multi-line string (except the first) by $spaces spaces.
     */
    private function indentBlock(string $block, int $spaces): string
    {
        if (! str_contains($block, PHP_EOL)) {
            return $block;
        }

        $pad = str_repeat(' ', $spaces);

        return implode(
            PHP_EOL,
            array_map(
                fn($line, $i) => $i === 0 ? $line : $pad . $line,
                explode(PHP_EOL, $block),
                array_keys(explode(PHP_EOL, $block)),
            ),
        );
    }

    private function sharedDataSection(string $sharedData): string
    {
        if ($sharedData === '' || $sharedData === 'Record<string, never>') {
            return '';
        }

        return '/* --- Shared Data --- */' . PHP_EOL . PHP_EOL
            . 'export interface SharedData ' . $sharedData;
    }

    private function routeListSection(array $routes): string
    {
        if (empty($routes)) {
            return '';
        }

        $lines = [];
        $lines[] = '/* --- Route List --- */';
        $lines[] = '';
        $lines[] = 'export const _routes: { [key in keyof Routes]: { method: Method, uri: string } } = {';

        foreach ($routes as $name => $route) {
            $lines[] = "  '" . $name . "': { method: '" . $route['method'] . "', uri: '" . $route['uri'] . "' },";
        }

        $lines[] = '}';

        return implode(PHP_EOL, $lines);
    }

    private function helpersSection(): string
    {
        return <<<'TS'
        /* --- Helpers --- */

        type Method = 'get' | 'post' | 'put' | 'patch' | 'delete' | 'options' | 'head';

        type RequiredKeys<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>

        export type PageProps<T extends keyof Routes> = InertiaPageProps & (
          Routes[T]['props'] extends never
            ? SharedData
            : Routes[T]['props'] & SharedData)

        export type RouteParams<T extends keyof Routes> =
          Routes[T]['params'] extends never
            ? never
            : Routes[T]['params']

        export type RouteBody<T extends keyof Routes> =
          Routes[T]['body'] extends never
            ? never
            : Routes[T]['body']

        export function route<T extends keyof Routes>(
          name: T,
          ...args: Routes[T]['params'] extends never ? [] : [params: Routes[T]['params']]
        ): { url: string; method: Method } {
          const [params] = args
          let url: string = window.location.origin + _routes[name].uri;
          if (params) {
            for (const [key, value] of Object.entries(params as Record<string, string | number>)) {
            url = url.replace(`{${key}}`, String(value))
            }
          }
          return { url, method: _routes[name].method };
        }
        TS;
    }
}
